#spring:
#  data:
#    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: note-service
#server:
#  port: 8082

spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
#      username: app-root
#      password: root123
      database: noteDb
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 8082
